<a href="https://colab.research.google.com/github/AyushGinoya/C/blob/main/LAB5_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf

x = tf.constant([[1., 2., 3.],
                 [4., 5., 6.]])

print(x)
print(x.shape)
print(x.dtype)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
(2, 3)
<dtype: 'float32'>


In [4]:
import numpy as np

In [5]:
# This will be an int32 tensor by default; see "dtypes" below.
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [6]:
# Let's make this a float tensor.
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [7]:
# If you want to be specific, you can set the dtype (see below) at creation time
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


In [8]:
# There can be an arbitrary number of
# axes (sometimes called "dimensions")
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


Ref. Link : https://www.kaggle.com/code/deepakvegda/quick-start-tensorflow



In [9]:
# the shape and the data types of the tensor is the main attribute you must check about the tensor.

# As and when we feed data in the model, we will see the importance of it.

In [10]:
import tensorflow as tf


x1 = tf.constant([[1., 2., 3.],
                 [4., 5., 6.]])

print(x)
print(x.shape)
print(x.dtype)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
(2, 3)
<dtype: 'float32'>


In [11]:
x + x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

The tensor can be updated by applying mathematical equations on it. It is easy. Just try the following

In [12]:
5 * x


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 5., 10., 15.],
       [20., 25., 30.]], dtype=float32)>

In [13]:
x @ tf.transpose(x)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [14]:
# tf.concat will take concatation of the given tensors, Try changing axis = 1. you may also try "tf.concat([x,x,x], axis=0)"
tf.concat([x, x], axis=0)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [15]:
tf.nn.softmax(x1, axis=-1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.09003057, 0.24472848, 0.66524094],
       [0.09003057, 0.24472848, 0.66524094]], dtype=float32)>

In [16]:
print(tf.reduce_sum([1,2,3]))
print(tf.reduce_sum(x))


tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(21.0, shape=(), dtype=float32)


**Typically, anywhere a TensorFlow function expects a Tensor as input, the function will also accept anything that can be converted to a Tensor using tf.convert_to_tensor. See below for an example.**

In [17]:
n = [1,2,3]
n

[1, 2, 3]

In [18]:
t = tf.convert_to_tensor(n)
t

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [19]:
if tf.config.list_physical_devices('GPU'):
    print("TensorFlow IS using the GPU")
else:
    print("TensorFlow IS NOT using the GPU")

TensorFlow IS NOT using the GPU


In [20]:
var = tf.Variable([0.0, 0.0, 0.0])

In [21]:
var.assign([1,2,3])

<tf.Variable 'UnreadVariable' shape=(3,) dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [22]:
# few examples of variable can be seen https://www.tensorflow.org/guide/variable
var.assign_add([1, 1, 1])

<tf.Variable 'UnreadVariable' shape=(3,) dtype=float32, numpy=array([2., 3., 4.], dtype=float32)>

In [27]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]])

In [28]:
print(tf.add(a, b), "\n")

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 



In [29]:
print(tf.multiply(a, b), "\n")

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 



In [30]:
print(tf.matmul(a, b), "\n")

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [31]:
print(a + b, "\n")
print(a * b, "\n")
print(a @ b, "\n")

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



Ref. Link - https://www.tensorflow.org/guide/keras AND https://www.tensorflow.org/guide/keras/sequential_model

tf.keras.Model class features built-in training and evaluation methods:


**tf.keras.Model.fit**: Trains the model for a fixed number of epochs.

**tf.keras.Model.predict**: Generates output predictions for the input samples.

**tf.keras.Model.evaluate**: Returns the loss and metrics values for the model; configured via the **tf.keras.Model.compile** method.